Netflix/bpftop

src/app.rs
src/main.rs

This PR refactors the App struct statistic gathering loop to be more efficient when handling the items vec and have less lock contention. Additionally, we now adjust the sleep duration to maintain a 1-second sample period, accounting for loop processing time.

Refactor thread loop in App struct for more accurate sample period

---

src/app.rs
src/main.rs

This fixes an out-of-bounds panic that happens when a selected eBPF program exits. We'll now clear the selection if the selected index is out-of-bounds. Also, we'll go back to the table view if the program we are currently charting exits.

Fix out-of-bounds selection bug

---

src/app.rs

using navigation keys (up, down) with an empty console results in a panic with out-of-band error.

fix: avoid crash when navigation keys used with an empty console

---

src/main.rs

Do not explicitly use the `white()` style to allow ratatui to use the terminal's foreground color.

Use the terminal's foreground color for all panels

---

.github/workflows/rust.yml
src/app.rs
src/main.rs

This change addresses some clippy warnings and adds clippy to the CI
```
warning: manual implementation of `Option::map`
--> src/app.rs:154:9
|
154 | /         match state.selected() {
155 | |             Some(i) => Some(items[i].clone()),
156 | |             None => None,
157 | |         }
| |_________^ help: try: `state.selected().map(|i| items[i].clone())`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_map
= note: `#[warn(clippy::manual_map)]` on by default
warning: this block may be rewritten with the `?` operator
--> src/main.rs:106:5
|
106 | /     if res.is_err() {
107 | |         return res;
108 | |     }
| |_____^ help: replace it with: `res.as_ref()?;`
|
= help: for further information visit …
```

Clippy warnings

---

Cargo.lock
Cargo.toml
src/main.rs

Adapts to lower kernels, no BPF_STATS_RUN_TIME, but has "/proc/sys/kernel/bpf_stats_enabled"

Adapts to lower kernels, no BPF_STATS_RUN_TIME, but has "/proc/sys/kernel/bpf_stats_enabled"

---

Cargo.lock
Cargo.toml
src/app.rs
src/main.rs

Added input fields for filtering `Name` and `Type` of BPF program. #5

Added filters for Name and Type

---

src/app.rs
src/bpf_program.rs
src/main.rs

Added functionality for sorting table based on a column. #2 
Most of the added code is for the new sorting feature. 
I modified the `BpfProgram` class with additional fields from the columns (period avg runtime, total avg runtime, events per sec, cpu time percent) so that they don't need to be computed twice when first displaying to UI, and then when sorting. 
I also added a `new` method for initializing a `BpfProgram` object so that it doesn't take up too much lines (which was in conjunction to the additional fields).

added column sorting feature on table

---

src/app.rs
src/main.rs

Previously we would use the index of the items collection to find the selected program. This worked until we added sorting, and now we don't get graphs if the selected program's index changes.
I took the opportunity to refactor a few things to use less shared state/locks and also fix this issue.  We will now store a copy of the selected program the moment a user enters the `Graph` mode. This means we will no longer need to share the table state with the background thread.
cc @tyrone-wu

Correctly display graphs when sorting is enabled

---

src/main.rs

Previously if there was a panic we would not disable BPF stats when using the procfs toggle (kernels older than 5.8). This adds a custom panic hook that disables BPF stats if needed, and then attempts to restore the terminal.

Add panic hook to disable BPF stats and restore terminal on panic

---

src/main.rs

If a user is using bpftop on a kernel older than 5.8, we will attempt to enable BPF stats globally using the procfs file `/proc/sys/kernel/bpf_stats_enabled`. With this change, we will only enable BPF stats via procfs if they are not already active. Thus, we will not modify the settings upon exit if the stats were previously enabled. This change ensures we do not deactivate BPF stats at shutdown if they were already turned on by the user before running bpftop.
I also did refactoring to make this logic easier to read.

Do not disable stats via procfs if already enabled

---

src/app.rs

bpftop now defaults to sorting by Total CPU % in descending order. This is the most useful sort order, as it shows the most CPU intensive BPF programs at the top of the list. This follows the same sort order as the `top` or `htop` tools.

Default sort order to Total CPU % descending order

---

src/main.rs

Small change to use the inbuilt `is_root()` method instead of extracting it manually from `getuid()`.
https://docs.rs/nix/latest/nix/unistd/struct.Uid.html#method.current

Update getuid root check

---

.github/workflows/rust.yml

Pin to the 2020 LTS to compile against glibc 2.31 and hence support a wider range of glibc versions than the current 2.35+ provided by the ubuntu-22.04 runner.
This is the oldest glibc supported out of the box from GitHub Runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

chore(ci): run build and release on 20.04

---

src/main.rs

When journald is not available, the program should not error out, but instead make noop log entries.

Do not error out if journald is not available

---

.github/workflows/rust.yml
Cross.toml
dockerfiles/Dockerfile.aarch64
dockerfiles/Dockerfile.x86_64

Previously we were building the binaries in CI using cargo directly. With this change we are using cross-rs to build the binaries and we now also target aarch64.

Use cross-rs to build binaries in CI

---

src/app.rs

To silence the clippy warning:
```
warning: assigning the result of `Clone::clone()` may be inefficient
--> src/app.rs:279:9
|
279 |         *self.graphs_bpf_program.lock().unwrap() = self.selected_program().clone();
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_from()`: `self.graphs_bpf_program.lock().unwrap().clone_from(&self.selected_program())`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
= note: `#[warn(clippy::assigning_clones)]` on by default
```

Use cloned_from() instead of clone() in app.rs

---

Cargo.lock
Cargo.toml

They had to be updated together to fix a build issue.

Update crossterm and tui-input to latest versions

---

README.md

Nix 24.11 is now the default and apparently 24.05 will be dropped in about a month. [https://discourse.nixos.org/t/nixos-24-11-released/56811](https://discourse.nixos.org/t/nixos-24-11-released/56811)
Is this fine to update?

Update Nix installation instructions (24.05 -> 24.11)

---

Cargo.lock
Cargo.toml
src/main.rs

This commit adds the clap crate to bpftop, enabling standardized --version and --help flags. The updated help output now explicitly instructs users to run the command with root privileges (e.g., using sudo).
Closes: https://github.com/Netflix/bpftop/issues/113

Add --version and --help flags

---

src/app.rs
src/main.rs

Closes #78  
Changes:
* Add [scrollbar widget](https://docs.rs/ratatui/latest/ratatui/widgets/struct.Scrollbar.html) and necessary fields to the `App` struct.
* Modify `app.next_program()` and `app.previous_program()` to
* Remove the wrapping navigation functionality. I think this is a confusing UX when a scrollbar is visible as it will jump up from bottom to top if a user indexes beyond the last program.
* Include logic to update the scrollbar position
TODO:

Add scrollbar to tabular view

---

.github/workflows/rust.yml

Update ubuntu-20.04 to ubuntu-latest in all workflow jobs as ubuntu-20.04 is deprecated.

Fix deprecated GitHub Actions runner

---

Cargo.lock
Cargo.toml

- Broadened version ranges for libbpf dependencies to improve compatibility with system-provided packages
- Allows libbpf-cargo and libbpf-rs versions >=0.24.4, <0.25  
- Allows libbpf-sys versions >=1.5.0, <1.6

Loosen libbpf dependency version requirements

---

.github/dependabot.yml

s only
Configures dependabot to only create PRs for security updates on Rust dependencies while allowing regular updates for GitHub Actions and devcontainers. This reduces noise from routine dependency bumps.

dependabot: limit cargo updates to security patche

---

Cargo.toml

Replace open-ended version ranges (>=X.Y.Z) with caret requirements (X.Y.Z) for all dependencies to follow best practices and address packaging concerns.

Use semver-compatible version constraints instead of open-ended ranges
